Dev CircleCI_v35

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,12 +45,14 @@ jobs:
       - run:
           name: Install Edge and Edge WebDriver
           command: |
+            set -ex  # Stop the script on errors and print each command
             sudo apt-get update && sudo apt-get install -y curl jq
             EDGE_DEB_URL=$(curl -s https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/ | grep -oP 'href="\K[^"]+' | grep -E 'amd64\.deb$' | sort -V | tail -n 1 | xargs -I{} echo "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/{}")
             echo "Downloading Microsoft Edge from: $EDGE_DEB_URL"
             wget -q -O edge.deb $EDGE_DEB_URL
             sudo dpkg -i edge.deb || sudo apt-get install -yf
-            LATEST_EDGE_DRIVER_URL=$(curl -s https://msedgedriver.azureedge.net/LATEST_STABLE | xargs -I{} echo "https://msedgedriver.azureedge.net/{}/edgedriver_linux64.zip")
+            LATEST_EDGE_DRIVER_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_STABLE)
+            LATEST_EDGE_DRIVER_URL="https://msedgedriver.azureedge.net/${LATEST_EDGE_DRIVER_VERSION}/edgedriver_linux64.zip"
             echo "Downloading Edge WebDriver from: $LATEST_EDGE_DRIVER_URL"
             wget -q -O edgedriver.zip $LATEST_EDGE_DRIVER_URL
             unzip edgedriver.zip -d edgedriver
